from fastapi import FastAPI
from pydantic import BaseModel
from database import run_query
from llm_handler import generate_cypher_query
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# -------------------------------
# CORS MIDDLEWARE (MOVE HERE)
# -------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -------------------------------
# REQUEST MODEL
# -------------------------------
class QueryRequest(BaseModel):
    query: str


# -------------------------------
# HOME ROUTE
# -------------------------------
@app.get("/")
def home():
    return {"message": "LLM Graph API Running"}


# -------------------------------
# ASK ENDPOINT
# -------------------------------
@app.post("/ask")
def ask_question(request: QueryRequest):

    user_query = request.query

    # ---------------- GUARDRAIL ----------------
    # Restrict to dataset/domain-related topics.
    allowed_keywords = [
        "order",
        "customer",
        "delivery",
        "invoice",
        "payment",
        "product",
        "material",
        "journal",
        "entry",
        "address",
        "billing"
    ]

    if not any(word in user_query.lower() for word in allowed_keywords):
        return {
            "message": "This system only supports dataset-related queries."
        }

    try:
        # ---------------- STEP 1: LLM → CYPHER ----------------
        cypher_query = generate_cypher_query(user_query)

        # CLEAN LLM OUTPUT
        cypher_query = cypher_query.replace("```cypher", "").replace("```", "").strip()

        print("\n🧠 Generated Cypher:", cypher_query)

        # ---------------- SAFETY CHECK ----------------
        if "MATCH" not in cypher_query:
            return {"error": "Invalid query generated by LLM"}

        # ---------------- STEP 2: RUN QUERY ----------------
        raw_result = run_query(cypher_query)

        # ---------------- STEP 3: CLEAN RESULT ----------------
        cleaned_result = []

        for record in raw_result:
            clean_record = {}

            for key, value in record.items():
                try:
                    # Neo4j node
                    if hasattr(value, "items"):
                        clean_record[key] = dict(value)
                    else:
                        clean_record[key] = str(value)
                except:
                    clean_record[key] = str(value)

            cleaned_result.append(clean_record)

        return {
            "user_query": user_query,
            "cypher": cypher_query,
            "result": cleaned_result
        }

    except Exception as e:
        print("\n❌ ERROR:", str(e))

        return {
            "error": str(e),
            "message": "Something went wrong while processing the query"
        }